### ISSUE TITLE
Usage Problem

### ISSUE THREAD

**Issue by emyoutis** [captainhook-git/plugin-composer#1]
I have docker implemented in my project. I've installed this package with composer inside of one of my containers. Now, I'm trying to commit my files outside the container an in the root directory of my project. 
But there is not any change after executing the `git commit` command.
What am I missing?

**Comment by heiglandreas** [comment]
Do you have PHP installed on your machine? Or only inside the container?

**Comment by emyoutis** [comment]
It is installed in the machine but its version does not match the container's.

**Comment by heiglandreas** [comment]
Can you post your `captainhook.json` file as well as your `composer.json` file so that we can have a look at your configuration and setup? That might make it easier to help you triage this issue.

**Comment by sebastianfeldmann** [comment]
What is the OS of your docker host System? Windows 10, MaxOS or Linux?

As long as your locally installed version is equal or greater to `7.1` you could certainly run `CaptainHook` with your locally installed `php`.

Here are some things you can do to troubleshoot.

### 1.  Check installation ###
Please make sure `CaptainHook` installed the hooks properly. For this you have to check your repositories `hooks` directory.

It is located in your git repository directory under `.git/hooks`.
Make sure you have for example a file called `.git/hooks/pre-commit` that contains an `CaptainHook` docker command.

### 2. Check docker command
If the hook files are installed correctly please make sure the docker commands in those hook files are correct. 

### 3. Try local installation
If you have a suffice `php` version installed locally, you can try to use the local `run-mode` just to make sure `CaptainHook` works as expected.

    $ vendor/bin/captainhook install --run-mode=local

After that check the hook files again, they now should contain some `php` code.

**Comment by sebastianfeldmann** [comment]
I'll close this issue due to inactivity.
Feel free to reopen it if you need any more assistance.
