### ISSUE TITLE
Change PHP version requirement to >=7.1

### ISSUE THREAD

**Issue by iquito** [captainhook-git/plugin-composer#12]
In the README the PHP version is stated as `>=7.1`, but in composer.json it is actually `^7.1`. Changing it to `>=7.1` would make it possible to start using it in PHP8. The same goes for `captainhook/captainhook` by the way, where the version constraint is `^7.2`.

Before the release of PHP8, many projects (like Symfony) have changed their PHP version requirements away from specific major versions to only specifying a minimum version, which makes more sense for the PHP constraint because you don't really want to prevent people from trying it in new PHP versions, and if there is a problem the early adopters (like me) will not be surprised anyway and report it, so it can be fixed.

**Comment by sebastianfeldmann** [comment]
Thanks for reporting the issue.

The problem is fixed for `captainhook` itself and for the `plugin-composer` package

**Comment by iquito** [comment]
Thanks! Now the version constraints of the helper packages still have PHP7 only version constraints:

- `sebastianfeldmann/camino`
- `sebastianfeldmann/cli`
- `sebastianfeldmann/git`

I think if you release a new version of those with a relaxed version constraint it should work.

**Comment by sebastianfeldmann** [comment]
Fixed ;)

**Comment by iquito** [comment]
Thanks! :-)
