### ISSUE TITLE
Force hooks install by default?

### ISSUE THREAD

**Issue by yassinedoghri** [captainhook-git/plugin-composer#16]
Hey 👋!

Checking the captainhook documentation, I saw it was possible to force the install (without any interaction) with the `-f` option. Now, correct me if I'm wrong, when using this plugin, it prompts all of the questions and doesn't force the install. I can't seem to find a way to have it configured here... how would I do that?

Also, as the [docs under "Post install command"](https://captainhookphp.github.io/captainhook/composer.html) suggests, shouldn't the install be forced by default in this plugin?

Anyways, thank you for captainhook and this plugin, it works great!

**Comment by sebastianfeldmann** [comment]
Overwriting stuff by default feels a bit aggressive and can lead to possible data loss.
But if you want to do it you can use the newly released `force-install` flag.

composer.json
```    
    "extra": {
      "captainhook": {
        "force-install": true
      }
    }
```
