### ISSUE TITLE
Hook install on Worktrees

### ISSUE THREAD

**Issue by f1r3ph03n1xX** [captainhook-git/plugin-composer#17]
if you are on a second worktree capt'n can't find the gitfolder
if this happens, composer install displays error message.

i think it would be better if composer install would just output a notice, because the githooks of the main worktree will still be executed.

**Comment by f1r3ph03n1xX** [comment]
https://github.com/captainhookphp/plugin-composer/pull/18

**Comment by sebastianfeldmann** [comment]
That´s how I like it. Report an issue and fix it yourself ;)

Thanks mate
