### ISSUE TITLE
`CI=true` is not working, `composer install` failing without `.git` folder

### ISSUE THREAD

**Issue by PHLAK** [captainhook-git/plugin-composer#19]
My company recently started using CaptainHook and have a shared testing server that we deploy to via [Envoyer](https://envoyer.io). This environment needs to have development packages installed for testing purposes which causes the `composer install` command to fail with the following error.

```
[RuntimeException]                                                                         
Shiver me timbers! CaptainHook could not install yer git hooks! (git directory not found)  
```

This makes sense due to the deployment not including the `.git` folder. When searching I found #13 and the corresponding PR which should allow us to set `CI=true` in our `.env` file, however this is having no effect.

Is there any other way to disable CaptainHook on a per-environment basis? 

On a related note, I'm also worried what other effects setting `CI=true` would have since this environment isn't strictly for CI. Would you accept a PR that adds a specific environment variable for disabling CaptainHook only (i.e. `DISABLE_CAPTAINHOOK`)?

**Comment by sebastianfeldmann** [comment]
I'm assuming you are using either the `plugin-composer` or `captainhook-phar` package.
The issue for you is that those Composer plugins will always at least try to install the hooks.

You can execute Composer like this

    composer install --no-plugins

As long as you are not using any other plugins that you need to execute this will disable all plugins and the Cap'n will not install the hooks.

**Comment by PHLAK** [comment]
Yes, we're using `plugin-composer`. The `--no-plugins` option is a good idea however it looks like we don't have control over this from Envoyer. :slightly_frowning_face: It would still be nice to have an environment variable _specifically_ for Captainhook.

**Comment by sebastianfeldmann** [comment]
I just pushed `plugin-composer` version 5.3.3 with the option to use the environment variable `CAPTAINHOOK_DISABLE` set to `true` to disable the plugin completely.

So you should be good to go if you run a `composer update` and setup the environment variable.

Hope that helps ;)

**Comment by PHLAK** [comment]
Awesome, thank you!
